[package]
name = "mictils"
version = "0.4.0"
edition = "2021"
authors = ["Tundra_Climate <tundra.tundere@gmail.com>"]
repository = "https://github.com/TundraClimate/mictils"
description = "mictils is util crate that contains various functions."
license = "MIT"
readme = "README.md"

[dependencies]
